import { SemanticColors } from '../../types/style';
import { BASE_COLORS } from './baseColors';

export const SEMANTIC_COLORS: SemanticColors = {
  // 主品牌色 - 使用蓝绿色体现健康专业
  PRIMARY_LIGHT: BASE_COLORS.TEAL_100,
  PRIMARY_MEDIUM: BASE_COLORS.TEAL_300,
  PRIMARY_MAIN: BASE_COLORS.TEAL_500,
  PRIMARY_DARK: BASE_COLORS.TEAL_700,
  PRIMARY_DARKER: BASE_COLORS.TEAL_900,
  
  // 辅助色 - 使用蓝色增加层次感
  SECONDARY_LIGHT: BASE_COLORS.BLUE_100,
  SECONDARY_MEDIUM: BASE_COLORS.BLUE_300,
  SECONDARY_MAIN: BASE_COLORS.BLUE_500,
  SECONDARY_DARK: BASE_COLORS.BLUE_700,
  SECONDARY_DARKER: BASE_COLORS.BLUE_900,
  
  // 状态色
  SUCCESS_LIGHT: BASE_COLORS.GREEN_100,
  SUCCESS_MAIN: BASE_COLORS.GREEN_500,
  SUCCESS_DARK: BASE_COLORS.GREEN_700,
  
  WARNING_LIGHT: BASE_COLORS.YELLOW_100,
  WARNING_MAIN: BASE_COLORS.YELLOW_500,
  WARNING_DARK: BASE_COLORS.YELLOW_700,
  
  ERROR_LIGHT: BASE_COLORS.RED_100,
  ERROR_MAIN: BASE_COLORS.RED_500,
  ERROR_DARK: BASE_COLORS.RED_700,
  
  INFO_LIGHT: BASE_COLORS.BLUE_100,
  INFO_MAIN: BASE_COLORS.BLUE_500,
  INFO_DARK: BASE_COLORS.BLUE_700,
  
  // 健康状态色
  HEALTH_EXCELLENT: BASE_COLORS.GREEN_500,
  HEALTH_GOOD: BASE_COLORS.GREEN_400,
  HEALTH_FAIR: BASE_COLORS.YELLOW_500,
  HEALTH_POOR: BASE_COLORS.ORANGE_500,
  HEALTH_CRITICAL: BASE_COLORS.RED_500,
};